### ISSUE TITLE
RuntimeError: Kernel sizes other than 7x7, 5x5, 3x3 and 1x1 not supported. got 1x3

### ISSUE THREAD

**Issue by kai981** [facebookresearch/DeltaCNN#4]
Hi, thank you so much for sharing the great work! 

I have been trying to implement the training code for efficientdet with DeltaCNN. However, I have encountered this following RuntimeError as shown: 

Kernel sizes other than 7x7, 5x5, 3x3 and 1x1 not supported. got 1x3
Traceback (most recent call last):
  File "/home/efficientdet/train_deltacnn.py", line 669, in <module>
    main()
  File "/home/efficientdet/train_deltacnn.py", line 417, in main
    train_metrics = train_epoch(
  File "/home/efficientdet/train_deltacnn.py", line 552, in train_epoch
    output = model(input, target)
  File "/home/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/efficientdet/effdet/bench_deltacnn.py", line 136, in forward
    class_out, box_out = self.model(x)
  File "/home/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/efficientdet/effdet/efficientdet_deltacnn.py", line 577, in forward
    x = self.backbone(x)
  File "/home/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/efficientdet/timm/models/efficientnet_deltacnn.py", line 620, in forward
    x = b(x)
  File "/home/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/anaconda3/lib/python3.9/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/efficientdet/timm/models/efficientnet_blocks_dc.py", line 143, in forward
    x = self.conv_dw(x)
  File "/home/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/efficientdet/src/deltacnn/sparse_layers.py", line 448, in forward
    return self._forward_delta_conv(input, first_iter)
  File "/home/efficientdet/src/deltacnn/sparse_layers.py", line 613, in _forward_delta_conv
    out = sparse_conv(
  File "/home/efficientdet/src/deltacnn/cuda_kernels.py", line 40, in sparse_conv
    sparse_conv_bias_wrapper_masked(x, filter, bias, out, mask, out_mask, stride, padding, dilation, groups, pad_mode_int, sub_tile_sparsity)
RuntimeError: Caught an unknown exception!
Killing subprocess 113535
Traceback (most recent call last):
  File "/home/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/anaconda3/lib/python3.9/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/anaconda3/lib/python3.9/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/anaconda3/lib/python3.9/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/anaconda3/bin/python', '-u', 'train_deltacnn.py', '--local_rank=0', '/home/datasets/unzipped/mot16', '--dataset', 'mot', '--model', 'efficientdet_d0', '--num-classes', '12', '-b', '4', '--lr', '.09', '--warmup-epochs', '5', '--amp', '--sync-bn', '--model-ema']' returned non-zero exit status 1.

I believed the line that caused the error is as followed, when depthwise convolution is used: 
**self.conv_dw = DCConv2d(32, 32, 3, stride=1, dilation=1, padding_mode='zeros', groups=32)** 

Could you please advice me on what might have caused this error? 
Thank you!

**Comment by dabeschte** [comment]
Hi!
This part of the code seems fine, but I am pretty sure that you either did not convert the weights or you forgot to derive a module which contains DeltaCNN layers from DCModule.

Btw training is not supported with DeltaCNN. This is an inference only framework. For training, please use cudnn and then use the final weights with DeltaCNN

**Comment by kai981** [comment]
Hi, thank you so much for the prompt reply! 
Could you please elaborate more about what you mean by "did not convert the weights"? 
Thank you!

**Comment by dabeschte** [comment]
I mean this step in the readme https://github.com/facebookresearch/DeltaCNN#33-weights-and-features-memory-layout

This is very important, because I store the weights in a much more efficient format than PyTorch does by default...at least when it comea to GPUs

**Comment by kai981** [comment]
Thank you so much for the clarification! :)
